### ISSUE TITLE
Sign_up [이성오님] - 머지 완료(충돌 문제 존재)

### ISSUE THREAD

**Issue by CureLatte** [CureLatte/pokemon_market#24]
app.py에서 충돌이 있었습니다. 

app.py 4번째 줄
common.py 파일이 import 안 됬습니다.

app.py 16번재 줄  
common.py 파일이 bp 등록이 안 됬습니다.

**Comment by seongolee** [comment]
김호님이 스타일 맞추려고 제화면 가져갔으니까 김호님한테 제가 전달할게요~
